[programs.localnet]
mev_payment = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
mev_distribution = "BsnxG8jiKuQxUegpkgcGx3EHs6GD7KrZJjBy53a1Ybaa"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
