[features]
seeds = false

[programs.localnet]
foo = "4tsETgKZoRbC9sZQH4VPqQ1UvhQLvfr7Jhxk5Eg5u3z8"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/" #"yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/"
#mocha -t 1000000 tests/