[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

# 7heq is the deployer here
[programs.testnet]
tip_distribution = "7QnFbRZajkym8mUh9rXuM5nKrPAPRfEU6W31izSWJDVh"
tip_payment = "3jarB2NVZc9KouEppPHoAf3v9y77H5R88nyfMLDUzuwm"

# Note: these are the keys in dev/ folder
# do not use these keys in production or you'll get wrecked
[programs.localnet]
tip_distribution = "3PX9z1qPj37eNZqH7e5fyaVDyG7ARqkjkYEe1a4xsBkA"
tip_payment = "6veFRUKJBNGMR58LEcKn5Bc6MR17WZF4rsgD4Lqq7fsU"

[workspace]
members = [
    "programs/tip-distribution",
    "programs/tip-payment"
]
exclude = ["programs/merkle-tree"]

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/"

[test.validator]
slots_per_epoch = "32"
ticks_per_slot = "1"
