#[features]
#seeds = false

[programs.localnet]
tip_payment = "Ek3SBXmGDvyvCGPYb98du8CNNjTomyiuc1wh7dMBw8gk"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/" #"yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/"
#mocha -t 1000000 tests/