[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.mainnet]
tip_distribution = "4R3gSG8BpU4t19KYj8CfnbtRpnT8gtk4dvTHxVRwc2r7"
tip_payment = "T1pyyaTNZsKv2WcRAB8oVnk93mLJw2XzjtVYqCsaHqt"

# 7heq is the deployer here
[programs.testnet]
tip_distribution = "7QnFbRZajkym8mUh9rXuM5nKrPAPRfEU6W31izSWJDVh"
tip_payment = "3jarB2NVZc9KouEppPHoAf3v9y77H5R88nyfMLDUzuwm"

# Note: these are the keys in dev/ folder
# do not use these keys in production or you'll get wrecked
[programs.localnet]
tip_distribution = "4R3gSG8BpU4t19KYj8CfnbtRpnT8gtk4dvTHxVRwc2r7"
tip_payment = "T1pyyaTNZsKv2WcRAB8oVnk93mLJw2XzjtVYqCsaHqt"

[workspace]
members = [
    "programs/tip-distribution",
    "programs/tip-payment"
]

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.{ts,js}"

[test.validator]
slots_per_epoch = "32"
ticks_per_slot = "1"
