[workspace]
members = [
    "programs/*",
    "initialize_tip_distribution",
    "initialize_tip_payment"
]

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
opt-level = 3
incremental = false
