[package]
name = "jito-protecc"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "jito_protecc"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
<<<<<<< HEAD
anchor-lang = "0.26.0"
=======
anchor-lang = { version = "0.27.0", features = ["init-if-needed"] }
anchor-spl = {version = "0.27.0", features = ["token"]}
>>>>>>> 28520ea (lil cleanup (#111))
