[package]
name = "vote-state"
version = "0.1.1-alpha.1"
edition = "2021"
description = "VoteState code copied from Solana."

[dependencies]
anchor-lang = "0.25.0"
bincode = "1.3.3"
serde = "1.0.138"
serde_derive = "1.0.103"
solana-program = "1.10"
