[package]
name = "vote-state"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = { path = "../../../../anchor/lang" }
bincode = "1.3.3"
serde = "1.0.138"
serde_derive = "1.0.103"
solana-program = { path = "../../../../sdk/program"}
